### ISSUE TITLE
Cannot `make install` unless already installed.

### ISSUE THREAD

**Issue by Sacro** [senorprogrammer/wtf#87]
```
which wtf | xargs rm
rm: missing operand
Try 'rm --help' for more information.
Makefile:9: recipe for target 'install' failed
make: *** [install] Error 123
```

`which wtf` will always fail if it's not already installed.

**Comment by jproffer** [comment]
you can get around this by just typing 'make' (without install) then 'go build'

**Comment by Sacro** [comment]
I was just following the Quickstart on the front page!

**Comment by Sacro** [comment]
`go build github.com/senorprogrammer/wtf: build output "wtf" already exists and is a directory`

**Comment by senorprogrammer** [comment]
Pretty sure @Sacro is correct and that's a bug. In the meantime you can run `go install`. It won't populate the build values in the System module correctly, but it should install. If you want the version values you can then run `make install`.

**Comment by senorprogrammer** [comment]
Fixed with this commit https://github.com/senorprogrammer/wtf/commit/a88a909e1060fbda54bdbbea6eb7166983aed419

**Comment by rmbrntt** [comment]
As a heads up, still getting a similar issue when following the `make install` instructions with that latest fix commit
```
make install
which wtf | xargs rm || true
which: no wtf in (...:/usr/local/go/bin:...
rm: missing operand
```

**Comment by fosspill** [comment]
Indeed, I'm experiencing this as well while following the guide

**Comment by senorprogrammer** [comment]
@fosspill Which OS are you on?

**Comment by fosspill** [comment]
Ubuntu 18.04

**Comment by deltaxflux** [comment]
Yeah time to improve the installer.
